[package]
name = "sdr_tuning"
version = "0.1.0"
edition = "2021"
build = "../../plugin_build.rs"

[[bin]]
name = "sdr-tuning-bench"
path = "src/main.rs"

[[bin]]
name = "scope-rate-bench"
path = "src/scope_bench.rs"

[[bin]]
name = "sdr-grid-bench"
path = "src/grid_bench.rs"

[[bin]]
name = "sdr-random-freq-bench"
path = "src/random_freq_bench.rs"

[[bin]]
name = "sdr-bladerf2-agc"
path = "src/bladerf2_agc.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
futuresdr = { path = "../..", features = ["plugin", "soapy", "bladerf1"] }
plugin_api = { path = "../../crates/plugin_api" }
rand = "0.9"
seify = { path = "../../crates/seify", default-features = false, features = ["soapy", "bladerf1"] }
