[package]
name = "sdr-cross-flowgraph-example"
version = "0.1.0"
edition = "2021"
build = "../../plugin_build.rs"

[[bin]]
name = "sdr_cross_fg"
path = "src/main.rs"

[[bin]]
name = "swap_bench"
path = "src/swap_bench.rs"


[dependencies]
futuresdr = { path = "../..", features = ["plugin"] }
plugin_host = { path = "../../crates/plugin_host" }
toml = "0.8"
