# WiFi Loopback (Software Loopback with Noise)
# TX Chain -> Noise -> RX Chain

[[blocks]]
name = "mac"
type = "wifi::Mac"
[[blocks.parameters]]
name = "src_addr"
type = "mac_addr"
value = "42:42:42:42:42:42"
[[blocks.parameters]]
name = "dst_addr"
type = "mac_addr"
value = "23:23:23:23:23:23"
[[blocks.parameters]]
name = "bssid"
type = "mac_addr"
value = "ff:ff:ff:ff:ff:ff"

[[blocks]]
name = "encoder"
type = "wifi::Encoder"
[[blocks.parameters]]
name = "mcs"
type = "Mcs"
value = "Qpsk_1_2"

[[blocks]]
name = "mapper"
type = "wifi::Mapper"

[[blocks]]
name = "fft_tx"
type = "Fft"
[[blocks.parameters]]
name = "size"
type = "usize"
value = 64
[[blocks.parameters]]
name = "direction"
type = "FftDirection"
value = "Inverse"
[[blocks.parameters]]
name = "normalize"
type = "bool"
value = true
[[blocks.parameters]]
name = "scaling"
type = "f32"
value = 0.138675  # sqrt(1.0/52.0)

[[blocks]]
name = "prefix"
type = "wifi::Prefix"
[[blocks.parameters]]
name = "pad_front"
type = "usize"
value = 10000
[[blocks.parameters]]
name = "pad_tail"
type = "usize"
value = 10000

[[blocks]]
name = "noise"
type = "Apply"
dtype = "Complex32"
output_type = "Complex32"
[[blocks.parameters]]
name = "function"
type = "closure"
value = "add_awgn"  # Normal(0.0, 0.01) noise

# Receiver Chain
[[blocks]]
name = "delay"
type = "Delay"
dtype = "Complex32"
[[blocks.parameters]]
name = "delay"
type = "usize"
value = 16

[[blocks]]
name = "complex_to_mag_2"
type = "Apply"
dtype = "Complex32"
output_type = "f32"
[[blocks.parameters]]
name = "function"
type = "closure"
value = "norm_sqr"

[[blocks]]
name = "float_avg"
type = "wifi::MovingAverage"
dtype = "f32"
[[blocks.parameters]]
name = "length"
type = "usize"
value = 64

[[blocks]]
name = "mult_conj"
type = "Combine"
dtype = "Complex32"
[[blocks.parameters]]
name = "function"
type = "closure"
value = "mult_conjugate"  # a * b.conj()

[[blocks]]
name = "complex_avg"
type = "wifi::MovingAverage"
dtype = "Complex32"
[[blocks.parameters]]
name = "length"
type = "usize"
value = 48

[[blocks]]
name = "divide_mag"
type = "Combine"
input1_type = "Complex32"
input2_type = "f32"
output_type = "f32"
[[blocks.parameters]]
name = "function"
type = "closure"
value = "norm_divide"  # a.norm() / b

[[blocks]]
name = "sync_short"
type = "wifi::SyncShort"

[[blocks]]
name = "sync_long"
type = "wifi::SyncLong"

[[blocks]]
name = "fft_rx"
type = "Fft"
[[blocks.parameters]]
name = "size"
type = "usize"
value = 64

[[blocks]]
name = "frame_equalizer"
type = "wifi::FrameEqualizer"

[[blocks]]
name = "symbol_sink"
type = "WebsocketPmtSink"
[[blocks.parameters]]
name = "port"
type = "u16"
value = 9002

[[blocks]]
name = "decoder"
type = "wifi::Decoder"

[[blocks]]
name = "blob_to_udp_frames"
type = "BlobToUdp"
[[blocks.parameters]]
name = "addr"
type = "string"
value = "127.0.0.1:55555"

[[blocks]]
name = "blob_to_udp_rftap"
type = "BlobToUdp"
[[blocks.parameters]]
name = "addr"
type = "string"
value = "127.0.0.1:55556"

# TX Chain Connections
[[connections]]
from = "mac"
from_port = "tx"
to = "encoder"
to_port = "tx"

[[connections]]
from = "encoder"
to = "mapper"

[[connections]]
from = "mapper"
to = "fft_tx"

[[connections]]
from = "fft_tx"
to = "prefix"

[[connections]]
from = "prefix"
to = "noise"

# RX Chain Connections - Branch 1 (delay path)
[[connections]]
from = "noise"
to = "delay"

# RX Chain Connections - Branch 2 (magnitude path)
[[connections]]
from = "noise"
to = "complex_to_mag_2"

[[connections]]
from = "complex_to_mag_2"
to = "float_avg"

# RX Chain Connections - Branch 3 (complex correlation path)
[[connections]]
from = "noise"
to = "mult_conj"
to_port = "in0"

[[connections]]
from = "delay"
to = "mult_conj"
to_port = "in1"

[[connections]]
from = "mult_conj"
to = "complex_avg"

# Combine paths
[[connections]]
from = "complex_avg"
to = "divide_mag"
to_port = "in0"

[[connections]]
from = "float_avg"
to = "divide_mag"
to_port = "in1"

# Sync blocks
[[connections]]
from = "delay"
to = "sync_short"
to_port = "in_sig"

[[connections]]
from = "complex_avg"
to = "sync_short"
to_port = "in_abs"

[[connections]]
from = "divide_mag"
to = "sync_short"
to_port = "in_cor"

[[connections]]
from = "sync_short"
to = "sync_long"

[[connections]]
from = "sync_long"
to = "fft_rx"

[[connections]]
from = "fft_rx"
to = "frame_equalizer"

[[connections]]
from = "frame_equalizer"
to = "decoder"

# Message Connections
[[message_connections]]
from = "frame_equalizer"
from_port = "symbols"
to = "symbol_sink"

[[message_connections]]
from = "decoder"
from_port = "rx_frames"
to = "blob_to_udp_frames"

[[message_connections]]
from = "decoder"
from_port = "rftap"
to = "blob_to_udp_rftap"

# Runtime Configuration
[runtime]
[[runtime.async_tasks]]
block = "mac"
port = "tx"
task = "periodic_sender"
interval_secs = 0.8
message_format = "Any"
message_pattern = "FutureSDR {seq}"
[[runtime.async_tasks.extra_params]]
name = "mcs"
type = "Mcs"
value = "Qam16_1_2"
